version: 2

docker_defaults: &docker_defaults
    docker:
        - image: circleci/node:8.11.1-browsers
    working_directory: ~/project/repo

attach_workspace: &attach_workspace
    attach_workspace:
        at: ~/project

to_persist: &to_persist
  root: ~/project
  paths:
    - repo/*

install_steps: &install_steps
    steps:
        - checkout
        - restore_cache:
            name: Restore node_modules cache
            keys:
                - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
                - dependency-cache-{{ .Branch }}-
                - dependency-cache-
        - run:
            name: Installing Dependencies
            command: yarn install
        - save_cache:
            name: Save node_modules cache
            key: dependency-cache-{{ .Branch }}-{{ checksum "yarn-lock" }}
            paths:
                - node_modules
        - persist_to_workspace:
            <<: *to_persist

jobs:
  checkout:
    <<: *docker_defaults
    <<: *install_steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          <<: *to_persist

  lint:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
        name: Lint JavaScript Code
        command: yarn lint

  lint_css:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
        name: Lint styled-components CSS code
        command: yarn lint:css

  # test:
  #     <<: *docker_defaults
  #     steps:
  #         - *attach_workspace
  #         - run:
  #             name: Test React components and generate coverage report
  #             command: yarn test:coverage --ci
  #         - persist_to_workspace:
  #           <<: *to_persist

  build:
      <<: *docker_defaults
      steps:
          - *attach_workspace
          - run:
              name: Build Solution
              command: yarn build
          - persist_to_workspace:
            <<: *to_persist


workflows:
  version: 2
  default:
    jobs:
      - checkout
      - lint:
        requires:
          - checkout
      - list_css:
          - checkout
      - build:
        requires:
          - lint
          - lint_css
