version: 2

docker_defaults: &docker_defaults
    docker:
        - image: circleci/node:8.11.1-browsers
    working_directory: ~/project/repo

attach_workspace: &attach_workspace
    attach_workspace:
        at: ~/project

install_steps: &install_steps
    steps:
        - checkout
        - restore_cache:
            name: Restore node_modules cache
            keys:
                - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
                - dependency-cache-{{ .Branch }}-
                - dependency-cache-
        - run:
            name: Installing Dependencies
            command: yarn install
        - save_cache:
            name: Save node_modules cache
            key: dependency-cache-{{ .Branch }}-{{ checksum "yarn-lock" }}
            paths:
                - node_modules
        - persist_to_workspace:
            root: ~/project
            paths:
                - repo

jobs:
    build:
        <<: *docker_defaults
        <<: *install_steps

    lint:
      <<: *docker_defaults
      steps:
        - *attach_workspace
        - run:
          name: Lint JavaScript Code
          command: yarn lint

    lint_css:
      <<: *docker_defaults
      steps:
        - *attach_workspace
        - run:
          name: Lint styled-components CSS code
          command: yarn lint:css

    test:
        <<: *docker_defaults
        steps:
            - *attach_workspace
            - run:
                name: Test React components and generate coverage report
                command: yarn test:coverage --ci
            - persist_to_workspace:
              <<: *to_persist

    bundle_check:
        <<: *docker_defaults
        steps:
            - *attach_workspace
            - run:
                name: Checking bundlesize
                command: yarn build

workflows:
    version: 2
    build_pipeline:
        jobs:
            - build
            - lint:
                requires:
                    - build
            - lint_css:
                requires:
                    - build
            - test:
                requires:
                    - build
            - bundle_check:
                requires:
                    - build
